global:
  port: 7777
applications:
  - name: TestServer
    remote: "https://github.com/wufe/polo-testserver"
    is_default: true
    target: http://{{container_id}}:3000
    commands:
      start:
        - command: docker build --no-cache -t polo-testserver:{{commit}} .
        - command: docker run -d --network polo-net polo-testserver:{{commit}} | head -c12
          output_variable: container_id
        - command: docker image prune -f
          continue_on_error: true
      stop:
        - command: "docker kill {{container_id}}"
          continue_on_error: true
    recycle:
      inactivity_timeout: 6000
    startup:
      retries: 5
    branches:
      - test: ^dev$
        watch: false
        main: false
      - test: feature/my-watched-feature
        watch: false